remove fzmp config, modify fzmp script
Cleanup fzmp script

diff --git a/home/.local/bin/fzmp b/home/.local/bin/fzmp
--- a/home/.local/bin/fzmp
+++ b/home/.local/bin/fzmp
@@ -1,20 +1,18 @@
 #!/usr/bin/env bash
 
-declare -r config_file="${XDG_CONFIG_DIR:-$HOME/.config}/fzmp/conf"
-
 usage() {
   LESS=-FEXR less <<HELP
 fzmp [OPTIONS]
 
 OPTIONS:
   -a --artist
-    search artist then filter by album (or F3 when running)
+    search artist then filter by album (or alt-3 when running)
   -A --all
-    search all songs in the library (or F2 when running)
+    search all songs in the library (or alt-2 when running)
   -g --genre
-    list genres (or F4 when running)
+    list genres (or alt-4 when running)
   -p --playlist
-    search the current playlist (or F1 when running)
+    search the current playlist (or alt-1 when running)
     playlist view has the following keybinds:
     >       go to the next song in the playlist
     <       go to the previous song in the playlist
@@ -22,57 +20,24 @@ OPTIONS:
     Ctrl-s  save current playlist
     Ctrl-p  toggle play/pause
   -P --playlists
-    list saved playlists (or F5 when running)
+    list saved playlists (or alt-5 when running)
   -h --help
     print this help
-
-CONFIGURATION:
-  A configuration file can be defined at $config_file
-  If a line begins with '#' it is treated as a comment and ignored
-  The configuration file reads the following options:
-
-  default_view
-    Must be 'artists' 'songs' 'playlist' or 'genres'
-  full_song_format
-    A format string to be passed directly to \`mpc format -f\` in
-    'playlist' and 'all' views. Defaults to:
-    [[[%artist% / ][[(%date%) ]%album% / ][[%track% - ][%title%]]]|%file%]
-    For colorized output try:
-    [[[\\e\\[32m%artist%\\e\\[0m / ][\\e\\[31m[(%date%) ]%album%\\e\\[0m / ][\\e\\[34m[%track% - ][%title%]\\e\\[0m]]|%file%]
-  playlist_view_key (default F1)
-  track_view_key (default F2)
-  artist_view_key (default F3)
-  genre_view_key (default F4)
-    allows customizing which keys fire the different views
-  findadd_key
-    adds all songs under the cursor by artist/genre/album
-    (default ctrl-space)
-  fzf_options
-    Command line options to be passed directly to fzf.
-    Changing this will override the default options:
-      --height='100%' +s -e -i --reverse --cycle
-    To use the jump feature of fzf you can try:
-      --bind=\`:jump --height='100%' +s -e -i --reverse --cycle
-    It also helps to have a bind for toggle-all:
-      --bind=ctrl-t:toggle-all --bind=\`:jump --height=100% +s -e -i --reverse --cycle
-    individual sessions can override with the environment variable FZMP_FZF_OPTIONS
-    fzmp will also inherit options from FZF_DEFAULT_OPTS
 HELP
 }
 
 declare default_filter='filter_by_playlist'
-declare track_format='[[[%artist% / ][[(%date%) ]%album% / ][[%track% - ][%title%]]]|%file%]'
+declare track_format='%Artist% %performer% - %title% (%Album% %date%)'
 declare -r album_listing="mpc find -f '%album%\t%track%\t%title%' artist {} | awk -F'\t' '{ if(album != \$1) { album=\$1; print album } printf \"  %2d. %s\n\", \$2, \$3 }'"
-declare -a config_err
 
 declare key_bindings
 declare -A bindings
 bindings=(
-  [playlist]='f1'
-  [track]='f2'
-  [artist]='f3'
-  [genre]='f4'
-  [playlists]='f5'
+  [playlist]='alt-1'
+  [track]='alt-2'
+  [artist]='alt-3'
+  [genre]='alt-4'
+  [playlists]='alt-5'
   [findadd]='ctrl-space'
 )
 
@@ -81,12 +46,15 @@ do_binding() {
   b=$(action_from_keybind "$1")
   shift
   case "$b" in
-    playlist) filter_by_playlist ;;
-    playlists) pick_playlist ;;
-    track) filter_by_songs ;;
-    artist) filter_by_artists ;;
-    genre) filter_by_genres ;;
-    *) [[ -n $1 ]] && { "$@"; return 0; } ;;
+  playlist) filter_by_playlist ;;
+  playlists) pick_playlist ;;
+  track) filter_by_songs ;;
+  artist) filter_by_artists ;;
+  genre) filter_by_genres ;;
+  *) [[ -n $1 ]] && {
+    "$@"
+    return 0
+  } ;;
   esac
   return 1
 }
@@ -135,22 +103,23 @@ has() {
     loud=1
     shift
   fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( loud > 0 )) && err "$c not found"
+  for c; do
+    c="${c%% *}"
+    if ! command -v "$c" &>/dev/null; then
+      ((loud > 0)) && err "$c not found"
       return 1
     fi
   done
 }
 
 is_running() {
-  pgrep "$1" &> /dev/null
+  pgrep "$1" &>/dev/null
 }
 
 fzf() {
   local opts
-  opts=( --reverse --cycle --height=100% )
-  [[ -v FZMP_FZF_OPTIONS ]] && opts=( $FZMP_FZF_OPTIONS )
+  opts=(--reverse --cycle --height=100%)
+  [[ -v FZMP_FZF_OPTIONS ]] && opts=($FZMP_FZF_OPTIONS)
   if has fzf; then
     command fzf \
       --inline-info \
@@ -167,44 +136,6 @@ fzf() {
   fi
 }
 
-parse_config_file() {
-  local line key val nr=0 e
-  while IFS= read -r line; do
-    (( ++nr ))
-    [[ -z "$line" || "$line" = '#'* ]] && continue
-    read -r key <<< "${line%% *}"
-    read -r val <<< "${line#* }"
-    if [[ -z "$val" ]]; then
-      config_err+=( "missing value for \"$key\" in config file on line $nr" )
-      continue
-    fi
-    case "$key" in
-      full_song_format) track_format="$val" ;;
-      fzf_options) FZMP_FZF_OPTIONS="$val" ;;
-      default_view)
-        if [[ "$val" =~ ^playlist$|^songs$|^artists$|^genres$|^playlists$ ]]; then
-          default_filter="filter_by_$val"
-        else
-          config_err+=( "unknown format \"$val\" in config file on line $nr" )
-          config_err+=( "default_view must be 'playlist' 'songs' 'artists' 'genres' or 'playlists'" )
-        fi ;;
-      playlist_view_key) bindings[playlist]="$val" ;;
-      artist_view_key) bindings[artist]="$val" ;;
-      track_view_key) bindings[track]="$val" ;;
-      genre_view_key) bindings[genre]="$val" ;;
-      playlists_view_key) bindings[playlists]="$val" ;;
-      findadd_key) bindings[findadd]="$val" ;;
-      *) config_err+=( "unknown key \"$key\" in config file on line $nr" )
-    esac
-  done < "$config_file"
-  if (( ${#config_err[@]} > 0 )); then
-    err 'there were errors parsing config file:'
-    for e in "${config_err[@]}"; do
-      err "  $e"
-    done
-  fi
-}
-
 filter_by_songs() {
   local choice
   mapfile -t choice < <(mpc search -f "%file%\t$track_format" filename '' |
@@ -216,8 +147,8 @@ filter_by_songs() {
       --expect="${key_bindings},enter" |
     cut -f1)
   case "${choice[0]}" in
-    'enter') printf '%s\n' "${choice[@]:1}" | add_songs play ;;
-    *) do_binding "${choice[0]}" || exit
+  'enter') printf '%s\n' "${choice[@]:1}" | add_songs play ;;
+  *) do_binding "${choice[0]}" || exit ;;
   esac
 }
 
@@ -230,10 +161,10 @@ filter_by_genres() {
       --bind="${bindings[findadd]}:execute-silent:mpc findadd genre {2..}" \
       --expect="${key_bindings},enter" |
     sed -r 's/^\s*[0-9]+\s*//')
-  (( ${#choice[@]} > 0 )) || die
+  ((${#choice[@]} > 0)) || die
   case "${choice[0]}" in
-    enter) filter_by_artist_from_genre "${choice[1]}" ;;
-    *) do_binding "${choice[0]}" || "$default_filter" ;;
+  enter) filter_by_artist_from_genre "${choice[1]}" ;;
+  *) do_binding "${choice[0]}" || "$default_filter" ;;
   esac
 }
 
@@ -246,10 +177,10 @@ filter_by_artist_from_genre() {
       --preview="$album_listing" \
       --expect="${key_bindings},enter" \
       --bind="${bindings[findadd]}:execute-silent:mpc findadd artist {}")
-  (( ${#choice[@]} > 0 )) || filter_by_genres
+  ((${#choice[@]} > 0)) || filter_by_genres
   case "${choice[0]}" in
-    enter) filter_by_album_from_artist "${choice[1]}" ;;
-    *) do_binding "${choice[0]}" || "$filter_by_genres" ;;
+  enter) filter_by_album_from_artist "${choice[1]}" ;;
+  *) do_binding "${choice[0]}" || "$filter_by_genres" ;;
   esac
 }
 
@@ -260,10 +191,10 @@ filter_by_artists() {
       --preview="$album_listing" \
       --bind="${bindings[findadd]}:execute-silent:mpc findadd artist {}" \
       --expect="${key_bindings},enter")
-  (( ${#choice[@]} > 0 )) || die
+  ((${#choice[@]} > 0)) || die
   case "${choice[0]}" in
-    'enter') filter_by_album_from_artist "${choice[1]}" ;;
-    *) do_binding "${choice[0]}" || "$default_filter" ;;
+  'enter') filter_by_album_from_artist "${choice[1]}" ;;
+  *) do_binding "${choice[0]}" || "$default_filter" ;;
   esac
 }
 
@@ -279,10 +210,10 @@ filter_by_album_from_artist() {
       --expect="${key_bindings},enter" \
       --bind="${bindings[findadd]}:execute-silent:mpc findadd album {2..} artist ${qartist}" \
       --delimiter='\t' |
-      cut -f2)
+    cut -f2)
   case "${choice[0]}" in
-    'enter') filter_songs_from_album "$artist" "${choice[1]}" ;;
-    *) do_binding "${choice[0]}" || filter_by_artists ;;
+  'enter') filter_songs_from_album "$artist" "${choice[1]}" ;;
+  *) do_binding "${choice[0]}" || filter_by_artists ;;
   esac
 }
 
@@ -299,8 +230,8 @@ filter_songs_from_album() {
       --expect="${key_bindings},enter" |
     cut -f1)
   case "${choice[0]}" in
-    'enter') printf '%s\n' "${choice[@]:1}" | add_songs play ;;
-    *) do_binding "${choice[0]}" || filter_by_album_from_artist "$artist" ;;
+  'enter') printf '%s\n' "${choice[@]:1}" | add_songs play ;;
+  *) do_binding "${choice[0]}" || filter_by_album_from_artist "$artist" ;;
   esac
 }
 
@@ -317,12 +248,21 @@ filter_by_playlist() {
       --expect="${key_bindings},>,<,ctrl-d,enter,ctrl-s" |
     cut -f1) || die
   case "${choice[0]}" in
-    '>') mpc -q next; filter_by_playlist ;;
-    '<') mpc -q prev; filter_by_playlist ;;
-    'enter') [[ -n "${choice[1]}" ]] && mpc -q play "${choice[@]:1}" && filter_by_playlist ;;
-    'ctrl-d') [[ -n "${choice[1]}" ]] && mpc -q del "${choice[@]:1}" && filter_by_playlist ;;
-    'ctrl-s') save_playlist; filter_by_playlist ;;
-    *) do_binding "${choice[0]}" || exit ;;
+  '>')
+    mpc -q next
+    filter_by_playlist
+    ;;
+  '<')
+    mpc -q prev
+    filter_by_playlist
+    ;;
+  'enter') [[ -n "${choice[1]}" ]] && mpc -q play "${choice[@]:1}" && filter_by_playlist ;;
+  'ctrl-d') [[ -n "${choice[1]}" ]] && mpc -q del "${choice[@]:1}" && filter_by_playlist ;;
+  'ctrl-s')
+    save_playlist
+    filter_by_playlist
+    ;;
+  *) do_binding "${choice[0]}" || exit ;;
   esac
 }
 
@@ -359,27 +299,28 @@ pick_playlist() {
       --bind='ctrl-space:execute-silent:mpc load {1}' \
       --expect="${key_bindings},ctrl-d,enter")
   case "${choice[0]}" in
-    'enter') mpc playlist -f '%file%' "${choice[1]}" | add_songs play && filter_by_playlist ;;
-    'ctrl-d')
-      tput clear
-      read -r -n 1 -p 'Are you sure you want to delete this playlist? (press y) ' confirm
-      if [[ ${confirm} = y ]]; then
-        mpc rm "${choice[1]}"
-        pick_playlist
-      fi ;;
-    *) do_binding "${choice[0]}" || exit
+  'enter') mpc playlist -f '%file%' "${choice[1]}" | add_songs play && filter_by_playlist ;;
+  'ctrl-d')
+    tput clear
+    read -r -n 1 -p 'Are you sure you want to delete this playlist? (press y) ' confirm
+    if [[ ${confirm} = y ]]; then
+      mpc rm "${choice[1]}"
+      pick_playlist
+    fi
+    ;;
+  *) do_binding "${choice[0]}" || exit ;;
   esac
 }
 
 add_songs() {
   local songs index
   mapfile -t songs
-  (( "${#songs[@]}" > 0 )) || die
+  (("${#songs[@]}" > 0)) || die
   printf '%s\n' "${songs[@]}" | mpc -q add
   [[ $1 == play ]] || return
   index=$(mpc playlist | wc -l)
-  if (( ${#songs[@]} > 1 )); then
-    index=$(( index - ${#songs[@]} + 1))
+  if ((${#songs[@]} > 1)); then
+    index=$((index - ${#songs[@]} + 1))
   fi
   mpc -q play "$index"
   filter_by_playlist
@@ -390,20 +331,37 @@ finish() {
 }
 trap finish EXIT SIGINT SIGTERM
 
-parse_config_file
 IFS=',' key_bindings="${bindings[*]}"
-key_bindings="${key_bindings/,${bindings[findadd]}}"
+key_bindings="${key_bindings/,${bindings[findadd]}/}"
 findadd_key="${bindings[findadd]}"
 
 while :; do
   case "$1" in
-    -A|--all) default_filter='filter_by_songs'; shift ;;
-    -a|--artist) default_filter='filter_by_artists'; shift ;;
-    -p|--playlist) default_filter='filter_by_playlist'; shift ;;
-    -P|--playlists) default_filter='pick_playlist'; shift ;;
-    -g|--genre) default_filter='filter_by_genres'; shift ;;
-    -h|--help) usage; exit ;;
-    *) break
+  -A | --all)
+    default_filter='filter_by_songs'
+    shift
+    ;;
+  -a | --artist)
+    default_filter='filter_by_artists'
+    shift
+    ;;
+  -p | --playlist)
+    default_filter='filter_by_playlist'
+    shift
+    ;;
+  -P | --playlists)
+    default_filter='pick_playlist'
+    shift
+    ;;
+  -g | --genre)
+    default_filter='filter_by_genres'
+    shift
+    ;;
+  -h | --help)
+    usage
+    exit
+    ;;
+  *) break ;;
   esac
 done
 
